name: Test Ziz API and SDK

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test-ziz:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 2.1.3
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Install dependencies
      run: |
        poetry install --with dev

    - name: Run tests for API and SDK
      run: |
        poetry run pytest tests/ -v --tb=short

    - name: Test basic package import
      run: |
        poetry run python -c "import ziz; print(f'Ziz package version: {ziz.__version__}')"

    - name: Test API main module
      run: |
        poetry run python -c "from ziz.api.main import app; print('API app created successfully')"

  test-api-docker-build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Test API Docker build
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: false
        cache-from: type=gha
        cache-to: type=gha,mode=max
        target: api
